#%RAML 1.0
---
title: Mobile Self Assessment
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile/self-assessment:
  /{utr}:
    uriParameters:
      utr:
        description: The UTR for the individual.
        type: string
        example: UTR123123
    get:
      displayName: Get the user's current liabilities
      description: This endpoint retrieves the SA user's liabilities
      is: [headers.acceptHeader]
      (annotations.scope): "read:native-apps-api-orchestration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:native-apps-api-orchestration" ] } ]
      queryParameters:
        journeyId:
          type: string
          required: true
      responses:
        200:
          body:
            application/json: